### ISSUE TITLE
After changing the Font its not working anymore

### ISSUE THREAD

**Issue by davidfrasch** [AliSoftware/OHAttributedStringAdditions#7]
Thanks for this great piece of Code!
I have a little Problem when i try to change the Font and the Text Size, because after that my Text (which should be bold) is only a normal Text.

This is my Code:

```
NSMutableAttributedString* htmlString = [NSMutableAttributedString attributedStringWithHTML:@"<b>Lorem Ipsum</b>"];

        [htmlString setFont:[UIFont fontWithName:@"Arial" size:14.0f]];

        self.textView = [UITextView new];
        self.textView.scrollEnabled = NO;

        [self addSubview:self.textView];

        self.textView.attributedText = htmlString;
        [self.textView sizeToFit];
```

**Comment by AliSoftware** [comment]
Well that's quite logical and the intended behavior: you set some style (using HTML) then override it using setFont afterwards.

The information you probably missed is that in any text engine, the bold and italic attributes are actually not an attribute of the _text_, like it's color for example, but is part of the _font_.  
So even in Word for example, if you write some text in Arial, then set it Bold, in fact it replaces the font with "Arial-Bold".
Arial is the _Font Family_, and "Arial-Regular", "Arial-Bold" and "Arial-Italics" are _variants_ of that font family.

So to implement the behavior you intended, you have multiple solutions:

#### 1. Avoid HTML
1. Use the bold font directly. You can use `+[UIFont fontWithFamily:@"Arial" size:14.0f bold:YES italic:NO]` as your font ([see here](https://github.com/AliSoftware/OHAttributedStringAdditions/blob/master/Source/UIFont%2BOHAdditions.h#L51-L54)).
2. Or use `setFontBold:` on your `NSMutableAttributedString` _after_ setting its font

In both these solutions, there will then be no need to use the `<b>` HTML tag (or even initialize the string using HTML, which is slower generally than using a plain string and add attributes yourself) to make it bold.

#### 2. Keep HTML

If you really need to initialize your string via HTML, you could:
1. set the font via HTML too (`<font>` tag)
2. or use `enumerateFontsInRange:includeUndefined:usingBlock:` that it will iterate over each run of your text that have different fonts (in case your HTML mix different fonts and you want to change them all but still keep the bold/italics/regular attribute of each) and alter the existing font to replace with the correct variant of the "Arial" font family

For example you can use the `-[UIFont symbolicTraits]` to get the traits (bold, italics, etc) of the current font being iterated, then use `[UIFont fontWithFamily:@"Arial" size:14 traits:currentTraits]` to apply the Arial font with the same bold/italics traits instead.

**Comment by davidfrasch** [comment]
Thank you very much for your fast response, your explanation was fantastic!! I need to keep the HTML because usally i get my Text from a Server (which includes HTML).  I changed my Code to this now, but it seems i can´t access the traits, because my Text still shows up without any bold:

```
NSMutableAttributedString* htmlString = [NSMutableAttributedString attributedStringWithHTML:@"<b>Lorem Ipsum</b>"];

        [htmlString enumerateFontsInRange:NSMakeRange(0,htmlString.length)
                  includeUndefined:YES
                        usingBlock:^(UIFont *font, NSRange range, BOOL *stop)
         {

             UIFontDescriptorSymbolicTraits traits = [font symbolicTraits];

             UIFont *newFont = [UIFont fontWithFamily:@"Arial" size:14.0f traits:traits];

             [htmlString setFont:newFont range:range];


         }];

        self.textView = [UITextView new];
        self.textView.scrollEnabled = NO;

        [self addSubview:self.textView];
        self.textView.attributedText = htmlString;
        [self.textView sizeToFit];
```

**Comment by AliSoftware** [comment]
Did you try to debug your code? Does the block in your enumeration actually properly get called, and if so how many iterations? What is the value of the `traits` you retrieve in each iteration ? If those traits you gather from the existing string do contain the bold attribute as expected, do the `newFont` find `Arial-Bold` or fail to find it and return another non-bold font variant instead? etc.

**Comment by davidfrasch** [comment]
So it seems the Problem is `symbolicTraits` and the Text from my Server.
When I use your String from the Example Project, everything works fine.

This is the Text from my Server:

```
htmlText = @"<b>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</b><br /><br />At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. <br /><br /><b>At vero eos et accusam et justo duo dolores et ea rebum.</b><br /> Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
```

The block gets called 4 times in a row, and my `newFont` variable is always:

```
<UICTFont: 0x18532f10> font-family: "Arial"; font-weight: normal; font-style: normal; font-size: 14.00pt
```

when i log `traits` i get this after each iteration:
 traits = 268435458
 traits = UIFontDescriptorClassOldStyleSerifs
 traits = 268435458
 traits = UIFontDescriptorClassOldStyleSerifs

**Comment by AliSoftware** [comment]
Mmmh strange, do you know what is the _original_ font generated by your HTML?

Trick: you could wrap your HTML returned by the server into a `<font face="Arial">…</font>` before parsing it, it should also do the trick in a simpler way.

**Comment by davidfrasch** [comment]
Thank you very much, with the little trick its working!
